"use client";

import { useState } from "react";
import { iconForFile } from "./file-icon";
import { previewKind } from "@/lib/files/preview";
import { cn } from "@/lib/utils";

/**
 * Shows a real image thumbnail for image files (generated by the
 * /api/files/[id]/thumbnail endpoint), falling back to a type icon for
 * everything else or if the thumbnail fails to load.
 */
export function FileThumb({
  id,
  name,
  mimeType,
  variant,
}: {
  id: string;
  name: string;
  mimeType: string;
  variant: "grid" | "list";
}) {
  const [failed, setFailed] = useState(false);
  const isImage = previewKind(mimeType, name) === "image";
  const { Icon, tint } = iconForFile(name, mimeType);
  const showImage = isImage && !failed;

  if (variant === "grid") {
    return (
      <div className="relative flex aspect-square w-full items-center justify-center overflow-hidden rounded-lg border border-border bg-surface-2">
        {showImage ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={`/api/files/${id}/thumbnail`}
            alt=""
            loading="lazy"
            onError={() => setFailed(true)}
            className="absolute inset-0 h-full w-full object-cover"
          />
        ) : (
          <Icon className={cn("h-9 w-9", tint)} />
        )}
      </div>
    );
  }

  return (
    <div className="flex h-9 w-9 shrink-0 items-center justify-center overflow-hidden rounded-md border border-border bg-surface-2">
      {showImage ? (
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={`/api/files/${id}/thumbnail`}
          alt=""
          loading="lazy"
          onError={() => setFailed(true)}
          className="h-full w-full object-cover"
        />
      ) : (
        <Icon className={cn("h-5 w-5", tint)} />
      )}
    </div>
  );
}
